---
driver:
  name: vagrant
  customize:
    memory: 2048
  synced_folders:
    - ["test/fixtures/packages", "/export/packages/slurm"]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[scicomp_slurm_test_cluster::repository]
      - recipe[scicomp_slurm_test_cluster::database]
      - recipe[scicomp_slurm_test_cluster::packages]
      - recipe[scicomp_slurm_test_cluster::config]
      - recipe[scicomp_slurm_test_cluster::slurmd]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
